function generateAffidavit(){

const lang = document.getElementById("lang").value;
const country = document.getElementById("country").value || "__________";
const name = document.getElementById("name").value || "__________";
const father = document.getElementById("father").value || "__________";
const address = document.getElementById("address").value || "__________";
const purpose = document.getElementById("purpose").value || "__________";

const today = new Date().toLocaleDateString();
const preview = document.getElementById("preview");

if(lang === "ar"){

preview.setAttribute("dir","rtl");

preview.innerHTML = `
<div class="doc-header">إفادة خطية</div>
<div class="doc-subheader">أمام كاتب العدل</div>

<p>أنا <b>${name}</b> ابن/ابنة <b>${father}</b>، المقيم في <b>${address}</b>، أقر وأصرح بما يلي:</p>
<p>1. أنني المصرح في هذه الإفادة.</p>
<p>2. أن الغرض من هذه الإفادة هو: <b>${purpose}</b>.</p>
<p>3. أن جميع المعلومات المذكورة صحيحة حسب علمي واعتقادي.</p>
<p>4. تم تحرير هذه الإفادة طواعية ولأغراض قانونية.</p>

<p>تم التحقق بموجب قوانين <b>${country}</b>.</p>
<p>المكان: __________</p>
<p>التاريخ: ${today}</p>

<div class="signature-section">
  <div class="signature-box">
    <div class="signature-line">توقيع المصرح</div>
  </div>
  <div class="signature-box">
    <div class="signature-line">توقيع وختم كاتب العدل</div>
    <div class="seal"></div>
  </div>
</div>

<div class="watermark">
Generated by Toolshub26 – Premium Legal Generator
</div>
`;

}else if(lang === "ur"){

preview.setAttribute("dir","rtl");

preview.innerHTML = `
<div class="doc-header">حلف نامہ</div>
<div class="doc-subheader">مجاز افسر کے روبرو</div>

<p>میں <b>${name}</b> ولد/دختر <b>${father}</b>، ساکن <b>${address}</b>، حلفاً بیان کرتا/کرتی ہوں کہ:</p>
<p>1. کہ میں اس حلف نامہ کا بیان کنندہ ہوں۔</p>
<p>2. کہ اس حلف نامہ کا مقصد ہے: <b>${purpose}</b>۔</p>
<p>3. کہ تمام معلومات درست ہیں۔</p>
<p>4. یہ حلف نامہ قانونی مقاصد کیلئے تحریر کیا گیا ہے۔</p>

<p>یہ حلف نامہ <b>${country}</b> کے قوانین کے تحت ہے۔</p>
<p>مقام: __________</p>
<p>تاریخ: ${today}</p>

<div class="signature-section">
  <div class="signature-box">
    <div class="signature-line">دستخط بیان کنندہ</div>
  </div>
  <div class="signature-box">
    <div class="signature-line">دستخط و مہر مجاز افسر</div>
    <div class="seal"></div>
  </div>
</div>

<div class="watermark">
Generated by Toolshub26 – Premium Legal Generator
</div>
`;

}else{

preview.removeAttribute("dir");

preview.innerHTML = `
<div class="doc-header">AFFIDAVIT</div>
<div class="doc-subheader">BEFORE THE NOTARY PUBLIC</div>

<p>I, <b>${name}</b>, son/daughter of <b>${father}</b>, residing at <b>${address}</b>, do hereby solemnly affirm:</p>
<p>1. That I am competent to swear this affidavit.</p>
<p>2. Purpose: <b>${purpose}</b>.</p>
<p>3. Information is true and correct.</p>
<p>4. Made voluntarily for lawful purposes.</p>

<p>Verified under the governing law of <b>${country}</b>.</p>
<p>Place: __________</p>
<p>Date: ${today}</p>

<div class="signature-section">
  <div class="signature-box">
    <div class="signature-line">Signature of Deponent</div>
  </div>
  <div class="signature-box">
    <div class="signature-line">Signature & Seal of Notary</div>
    <div class="seal"></div>
  </div>
</div>

<div class="watermark">
Generated by Toolshub26 – Premium Legal Generator
</div>
`;

}

}
